import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
const satoshi = localFont({
  src: "./fonts/satoshi-regular.ttf",
  variable: "--font-satoshi",
  weight: "400",
});

const satoshiBold = localFont({
  src: "./fonts/satoshi-bold.ttf",
  variable: "--font-satoshi-bold",
  weight: "700",
});

const satoshiItalic = localFont({
  src: "./fonts/satoshi-italic.ttf",
  variable: "--font-satoshi-italic",
  weight: "400",
  style: "italic",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${satoshiBold.variable} ${satoshiItalic} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
