import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Inter_Tight } from "next/font/google";
import "./globals.css";
import React from "react";
import ActiveSectionContextProvider from "@/context/ActiveSectionContext";
import ThemeContextProvider from "@/context/ThemeContext";
const satoshi = localFont({
  src: "./fonts/satoshi.ttf",
  variable: "--font-satoshi",
  weight: "400",
});

const satoshiBold = localFont({
  src: "./fonts/satoshi-bold.ttf",
  variable: "--font-satoshi-bold",
  weight: "700",
});

const satoshiItalic = localFont({
  src: "./fonts/satoshi-italic.ttf",
  variable: "--font-satoshi-italic",
  weight: "400",
  style: "italic",
});
// const interTight  = Inter_Tight()
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ActiveSectionContextProvider>
        <ThemeContextProvider>
          <body
            className={`${satoshi.variable} ${satoshiBold.variable} ${satoshiItalic.variable} relative z-0 bg-gray-50  pt-28 text-gray-950 antialiased dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90 sm:pt-36`}
          >
            {/* Background Layer */}
            <div
              className="fixed inset-0 -z-10 bg-landing-pattern bg-cover bg-no-repeat opacity-25"
              aria-hidden="true"
            ></div>{" "}
            <div className="relative z-10">{children}</div>
          </body>
        </ThemeContextProvider>
      </ActiveSectionContextProvider>
    </html>
  );
}
